# version: 3.1 - Updated for Python 3.13 compatibility
services:
  - type: web
    name: bybit-trading-bot
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: "3.10.12"
    envVars:
      # Bot & mode
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: MODE
        value: "LIVE"
      - key: ALLOW_LIVE
        value: "1"
      - key: MIN_CAPITAL_FOR_LIVE
        value: "11"
      - key: DRY_RUN_LIVE
        value: "0"
      
      # Bybit API
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_API_SECRET
        sync: false
      
      # Strategy & risk
      - key: CONTRACT_CODE
        value: "BTCUSDT"
      - key: START_CAPITAL
        value: "9.0"
      - key: RISK_PERCENT
        value: "0.5"
      - key: LEVERAGE
        value: "15"
      - key: RSI_PERIOD
        value: "14"
      - key: SMA_PERIOD
        value: "200"
      - key: STOP_LOSS_PCT
        value: "0.02"
      - key: TAKE_PROFIT_PCT
        value: "0.04"
      - key: DAILY_LOSS_LIMIT_PCT
        value: "10.0"
      - key: MAX_TRADES_PER_DAY
        value: "50"
      - key: MIN_TRADE_USD
        value: "0.1"
      
      # Donation system
      - key: DONATION_ENABLED
        value: "1"
      - key: DONATION_PERCENT
        value: "5"
      - key: DONATION_LOG_FILE
        value: "donations.log"
      - key: DONATION_PENDING_FILE
        value: "donations_pending.json"
      - key: DONATION_NOTIFY
        value: "1"
      
      # Misc
      - key: DATA_DIR
        value: "data"
      - key: API_HOST
        value: "api.bybit.com"
      - key: PYTHON_VERSION
        value: "3.10.12"
    
    # Health check to prevent sleep on free plan
    healthCheckPath: /health
    autoDeploy: true

# Create data directory for logs and files
disk:
  name: data
  mountPath: /data
  sizeGB: 1